// Generates public/index.js — the module that public/worker.js imports.
// Combines: the built single-file web app (dist/index.html), the guide/setup
// data from src/content.ts, and the raw source of worker.js itself (served
// back at GET /worker.js so admins can download it).
import { readFileSync, writeFileSync } from 'node:fs';
import { transformSync } from 'esbuild';

const html = readFileSync('dist/index.html', 'utf8');
const workerSource = readFileSync('public/worker.js', 'utf8');

// src/content.ts has no external imports, so it can be transpiled and
// executed standalone to pull out the plain data arrays it exports.
const ts = readFileSync('src/content.ts', 'utf8');
const { code } = transformSync(ts, { loader: 'ts', format: 'cjs' });
const mod = { exports: {} };
new Function('module', 'exports', code)(mod, mod.exports);
const { GUIDES, RELEASES, SETUP } = mod.exports;

const out = `// Auto-generated by scripts/build-worker.mjs — do not edit by hand.
export const guides = ${JSON.stringify(GUIDES)};
export const releases = ${JSON.stringify(RELEASES)};
export const setup = ${JSON.stringify(SETUP)};
export const workerSource = ${JSON.stringify(workerSource)};
export default ${JSON.stringify(html)};
`;

writeFileSync('public/index.js', out);
console.log(`Generated public/index.js (${(out.length / 1024).toFixed(0)} KB)`);
