export type Guide = { name: string; fa: string; group: string; description: string; descriptionFa: string; code: string; note?: string };
export const STARTER = `# Welcome to TeleRich ✨

Turn your ideas into **beautiful Telegram messages**.
Write, preview, and publish — all in one place.

### A little formatting goes a long way
**Bold ideas.** *A different perspective.*
<mark>Something worth highlighting.</mark>

> Great messages deserve great formatting.

### Built for more
- Rich text & interactive buttons
- Media, tables & beautiful layouts
- Your bot. Your channels. Your style.

<tg-button-row>
  <tg-button type="url" style="success" url="https://t.me">Explore TeleRich ↗</tg-button>
  <tg-button type="copy_text" text="Hello from TeleRich!">Copy text</tg-button>
</tg-button-row>`;
const text: [string,string,string,string,string][] = [
 ['Bold','متن ضخیم','<b>Bold text</b>','Emphasize important text. Nest with italic or underline.','برای تأکید بر متن؛ قابل ترکیب با ایتالیک و زیرخط.'],
 ['Italic','ایتالیک','<i>Italic text</i>','Use italic text for emphasis, titles, or a different voice.','متن مورب برای تأکید یا عنوان.'],
 ['Underline','زیرخط','<u>underlined text</u>, <ins>underlined text</ins>','Both u and ins underline their content.','هر دو تگ u و ins زیر متن خط می‌کشند.'],
 ['Strikethrough','خط‌خورده','<s>Old idea</s> New idea','Mark removed or replaced text. Markdown: ~~text~~.','برای متن حذف‌شده؛ در مارک‌داون از ~~text~~ استفاده کنید.'],
 ['Spoiler','اسپویلر','<tg-spoiler>A little secret</tg-spoiler>','Content is concealed until the reader clicks it. Markdown: ||text||.','محتوا تا زمان کلیک پنهان می‌ماند.'],
 ['DateTime','تاریخ و زمان','<tg-time unix="1647531900" format="wDT">22:45 tomorrow</tg-time>','Use a Unix timestamp in seconds. Telegram localizes the date and time; the preview uses your browser locale.','زمان یونیکس برحسب ثانیه است؛ تلگرام زمان را با منطقه زمانی کاربر نمایش می‌دهد.'],
 ['TextMention','منشن کاربر','<a href="tg://user?id=777000">Telegram</a>','Mention a user by numeric ID, subject to their privacy settings.','منشن با شناسه عددی، وابسته به تنظیمات حریم خصوصی کاربر.'],
 ['Subscript','زیرنویس','H<sub>2</sub>O','Render text below the baseline, for chemical formulas and indices.','نمایش زیر خط پایه برای فرمول شیمیایی و اندیس.'],
 ['Superscript','بالانویس','x<sup>2</sup> + y<sup>2</sup>','Render powers or ordinal markers above the baseline.','نمایش توان و شماره بالای خط پایه.'],
 ['Marked','هایلایت','<mark>Something worth highlighting.</mark>','Highlight text. Markdown equivalent: ==text==.','برجسته کردن با پس‌زمینه؛ در مارک‌داون ==text==.'],
 ['Code','کد','<code>console.log("Hello")</code>','Inline monospaced code. Use pre for a multiline code block.','کد تک‌خطی با فونت ثابت؛ برای چند خط از pre استفاده کنید.'],
 ['CustomEmoji','ایموجی سفارشی','<tg-emoji emoji-id="5368324170671202286">👍</tg-emoji>','Supply a valid custom emoji identifier. The web preview shows its fallback emoji; Telegram resolves the asset.','شناسه معتبر ایموجی را وارد کنید. وب ایموجی جایگزین و تلگرام فایل اصلی را نشان می‌دهد.'],
 ['MathematicalExpression','فرمول ریاضی','<tg-math>\\frac{a^2 + b^2}{c}</tg-math>','Inline LaTeX, rendered with KaTeX in the preview. Use $...$ in Markdown.','فرمول درون‌خطی LaTeX؛ رندر وب با KaTeX انجام می‌شود.'],
 ['Url','پیوند','<a href="https://telegram.org">Visit Telegram ↗</a>','Link text to an HTTPS or supported tg:// destination.','پیوند به آدرس HTTPS یا آدرس پشتیبانی‌شده tg://.'],
 ['EmailAddress','ایمیل','<a href="mailto:hello@example.com">hello@example.com</a>','Email addresses are detected automatically unless skip_entity_detection is enabled.','ایمیل‌ها به صورت خودکار شناسایی می‌شوند مگر تشخیص خودکار غیرفعال باشد.'],
 ['PhoneNumber','شماره تلفن','<a href="tel:+12025550123">+1 202 555 0123</a>','A phone number link opens the device dialer.','پیوند شماره تلفن، شماره‌گیر دستگاه را باز می‌کند.'],
 ['BankCardNumber','شماره کارت','4111 1111 1111 1111','Telegram can recognize bank card numbers. Use test values only in demos.','تلگرام شماره کارت را تشخیص می‌دهد. در نمونه فقط از شماره آزمایشی استفاده کنید.'],
 ['Mention','نام کاربری','@telegram','Telegram detects @username mentions and opens the corresponding profile.','تلگرام نام کاربری را شناسایی و پروفایل را باز می‌کند.'],
 ['Hashtag','هشتگ','#TeleRich','Use a hashtag to group and discover related messages.','هشتگ برای دسته‌بندی و جست‌وجوی پیام‌ها.'],
 ['Cashtag','نماد سهام','$TELE','A dollar-prefixed symbol is detected as a cashtag.','نماد با پیشوند دلار به عنوان کش‌تگ شناسایی می‌شود.'],
 ['BotCommand','دستور ربات','/start','Commands start with /. Your bot handles them through message updates.','دستور با / شروع می‌شود و از طریق آپدیت پیام به ربات می‌رسد.'],
 ['Button','دکمه ریچ','<p>Inline buttons: <tg-button type="url" style="success" url="https://t.me">url</tg-button> <tg-button type="url" url="tg://user?id=777000">user</tg-button> <tg-button type="callback_data" style="link" data="callback">callback with the date <tg-time unix="1647531900" format="wDT">22:45 tomorrow</tg-time> and the custom emoji <tg-emoji emoji-id="5368324170671202286">👍</tg-emoji></tg-button> <tg-button type="web_app" style="danger" url="https://telegram.org">Mini App (private chats only)</tg-button> <tg-button type="switch_inline_query" style="primary" query="inline">inline</tg-button> <tg-button type="switch_inline_query_current_chat" query="inline 2">inline 2</tg-button> <tg-button type="switch_inline_query_chosen_chat" query="inline 3" allow-user-chats allow-bot-chats allow-group-chats allow-channel-chats>inline 3</tg-button> <tg-button type="copy_text" text="...copy">Copy</tg-button> <tg-button type="disabled">Disabled</tg-button></p>','10.3: rich buttons come in two placements. Placed inline like this, a button flows inside a paragraph alongside regular text and other entities. Every action type works inline — url, callback_data, web_app, the three switch_inline_query variants, copy_text and disabled. Styles: primary, success, danger; link is callback-only. Colors follow the Telegram theme, not arbitrary hex values. For the normal, row-grouped placement, see Buttons below.','نسخه ۱۰.۳: دکمه‌های ریچ دو حالت چیدمان دارند. در این حالت درون‌خطی، دکمه داخل پاراگراف و کنار متن و سایر عناصر قرار می‌گیرد. همه نوع عمل به‌صورت درون‌خطی کار می‌کند: url، callback_data، web_app، سه حالت switch_inline_query، copy_text و disabled. رنگ‌ها primary، success و danger هستند؛ link فقط برای callback است. رنگ دلخواه هگز پشتیبانی نمی‌شود. برای حالت عادی و ردیفی به بخش «دکمه‌ها» مراجعه کنید.'],
 ['Anchor','لنگر','<a name="chapter-1"></a><h3>Chapter 1</h3>','Create a named target inside the message. Use an anchor link to jump here.','یک مقصد نام‌گذاری‌شده در پیام ایجاد کنید.'],
 ['AnchorLink','پیوند لنگر','<a href="#chapter-1">Jump to chapter 1</a>','Link to an anchor in the same rich message. The target name must match.','پیوند به لنگر داخل همان پیام؛ نام مقصد باید یکسان باشد.'],
 ['Reference','پاورقی','A useful fact[^note].\n\n[^note]: The supporting explanation.','Define a footnote in Rich Markdown with [^id]: and reference it using [^id].','تعریف پاورقی در مارک‌داون با [^id]: و ارجاع با [^id].'],
 ['ReferenceLink','ارجاع پاورقی','Read the source[^source].\n\n[^source]: https://core.telegram.org/bots/api','A reference link connects text to a footnote definition. IDs must be unique.','متن را به تعریف پاورقی متصل می‌کند؛ شناسه باید یکتا باشد.'],
];
export const GUIDES: Guide[] = text.map(([name,fa,code,description,descriptionFa])=>({ name:'RichText'+name,fa,code,description,descriptionFa,group:'Rich text' }));
const blocks: [string,string,string,string,string][] = [
 ['SectionHeading','عنوان‌ها','<h1>Heading 1</h1>\n<h2>Heading 2</h2>\n<h3>Heading 3</h3>\n<h4>Heading 4</h4>\n<h5>Heading 5</h5>\n<h6>Heading 6</h6>','Six heading levels. Markdown uses one to six # characters.','شش سطح عنوان؛ در مارک‌داون از یک تا شش # استفاده کنید.'],
 ['Paragraph','پاراگراف','<p>A paragraph with <b>rich text</b>.</p>','Separate blocks of text with paragraphs or blank lines in Markdown.','متن‌ها را با پاراگراف یا خط خالی جدا کنید.'],
 ['List','فهرست','- milk\n- eggs\n- [ ] todo\n- [x] done\n\n1. wake up\n2. ship it','Unordered, ordered and task lists. List items support nested rich text.','فهرست مرتب، نامرتب و کارها؛ قابل استفاده با متن قالب‌بندی‌شده.'],
 ['BlockQuotation','نقل‌قول تو در تو','<blockquote>A quote<blockquote>A nested thought</blockquote></blockquote>','Nest blockquote tags to create multiple levels of quotation.','با قرار دادن تگ‌های blockquote داخل هم، نقل‌قول چندسطحی بسازید.'],
 ['PullQuotation','نقل‌قول برجسته','<aside>Pull quote<cite>The Author</cite></aside>','Pull quotes emphasize a passage. cite identifies its author.','نقل‌قول برجسته؛ cite برای نام نویسنده است.'],
 ['ExpandableBlockQuotation','نقل‌قول بازشونده','<blockquote expandable>Click to expand this quotation.\nMore content inside.</blockquote>','10.3: a quotation that can expand or collapse. The browser preview uses an interactive disclosure.','نسخه ۱۰.۳: نقل‌قول قابل باز و بسته شدن.'],
 ['Details','بخش بازشونده','<details><summary>Closed by default</summary>Hidden content</details>\n<details open><summary>Open by default</summary>Visible content</details>','summary provides the label. Add open to show content initially.','summary عنوان بخش است؛ open محتوا را از ابتدا نشان می‌دهد.'],
 ['Table','جدول','<table bordered striped compact><caption>Table caption</caption>\n<tr><th>Feature</th><th>Status</th></tr>\n<tr><td align="left">Rich buttons</td><td align="center">Available</td></tr>\n<tr><td colspan="2">Merged columns</td></tr>\n<tr><td rowspan="2" valign="top">Two rows</td><td>First</td></tr>\n<tr><td>Second</td></tr></table>','bordered adds borders; striped alternates rows; compact reduces padding (is_compact in block JSON). colspan/rowspan merge cells. align: left/center/right; valign: top/middle/bottom. Keep a consistent grid when merging.','bordered برای حاشیه، striped برای سطرهای راه‌راه و compact برای فاصله کمتر. colspan و rowspan ادغام سلول‌ها هستند. align تراز افقی و valign تراز عمودی است؛ ساختار شبکه را حفظ کنید.'],
 ['MathematicalExpression','بلوک فرمول','<tg-math-block>E = mc^2</tg-math-block>','Display a LaTeX formula in its own block. Markdown: $$...$$.','فرمول LaTeX در یک بلوک مستقل؛ در مارک‌داون $$...$$.'],
 ['Preformatted','بلوک کد','<pre><code class="language-javascript">const hello = "TeleRich";\nconsole.log(hello);</code></pre>','Preserve whitespace in multiline code. Set language-* for the language label.','حفظ فاصله‌ها در کد چندخطی؛ زبان را با language-* مشخص کنید.'],
 ['Divider','جداکننده','<hr>','Separate sections visually. Markdown equivalent: ---.','جداکننده بخش‌ها؛ معادل مارک‌داون ---.'],
 ['Footer','پانویس','<footer>Made with TeleRich · 2026</footer>','A muted footer for attribution and supplementary text.','پانویس برای اطلاعات تکمیلی و نام نویسنده.'],
 ['Map','نقشه','<tg-map lat="41.9" long="12.5" zoom="14"/>','Set latitude, longitude and zoom. The web preview embeds OpenStreetMap; Telegram uses its native map renderer.','عرض جغرافیایی، طول و بزرگ‌نمایی را تنظیم کنید؛ وب از OpenStreetMap و تلگرام از نقشه بومی استفاده می‌کند.'],
 ['Photo','عکس','<img src="https://telegram.org/example/photo.jpg"/>','Use a public image URL or media mapped via tg://photo?id=. Example URLs are placeholders; supply your own asset.','آدرس عمومی عکس یا مدیای نگاشت‌شده tg://photo?id=؛ لینک نمونه را با فایل واقعی جایگزین کنید.'],
 ['Video','ویدیو','<video src="https://telegram.org/example/video.mp4"/>','Embed a publicly accessible video. The browser includes playback controls.','ویدیو با لینک عمومی؛ در وب کنترل پخش دارد.'],
 ['Audio','صوت','<audio src="https://telegram.org/example/audio.mp3"/>','Embed audio with an HTTPS URL or a mapped Telegram media ID.','صوت با لینک HTTPS یا شناسه مدیای نگاشت‌شده.'],
 ['VoiceNote','پیام صوتی','![](https://telegram.org/example/audio.ogg)','An OGG voice note. InputMediaVoiceNote was added in 10.2.','پیام صوتی OGG؛ کلاس InputMediaVoiceNote از نسخه ۱۰.۲.'],
 ['Animation','انیمیشن','<img src="https://telegram.org/example/animation.gif"/>','Use a GIF or a supported animation asset.','از GIF یا فایل انیمیشن پشتیبانی‌شده استفاده کنید.'],
 ['Collage','کلاژ','<tg-collage><img src="https://telegram.org/example/photo.jpg"/><img src="https://telegram.org/example/photo.jpg"/><figcaption>Caption<cite>The Author</cite></figcaption></tg-collage>','Group images into a collage. figcaption and cite add a caption and attribution. Replace example URLs with real media.','چند عکس در کلاژ؛ figcaption برای توضیح و cite برای نویسنده. لینک‌ها را با فایل واقعی عوض کنید.'],
 ['Slideshow','اسلایدشو','<tg-slideshow><img src="https://telegram.org/example/photo.jpg"/><video src="https://telegram.org/example/video.mp4"/><figcaption>Slideshow caption<cite>The Author</cite></figcaption></tg-slideshow>','Combine photos and videos. Navigate between slides in the live preview.','ترکیب عکس و ویدیو؛ جابه‌جایی بین اسلایدها در پیش‌نمایش.'],
 ['Document','سند','<a href="tg://document?id=report">Download report</a>','10.3: documents can be embedded. Map the id to an InputRichMessageMedia document in rich_message.media; the link alone does not upload a file.','نسخه ۱۰.۳: سند؛ شناسه باید به document در rich_message.media نگاشت شود. پیوند به تنهایی فایل را آپلود نمی‌کند.'],
 ['Buttons','دکمه‌ها','<tg-button-row align="left">\n  <tg-button type="url" url="https://t.me">url</tg-button>\n  <tg-button type="url" style="success" url="tg://user?id=777000">user</tg-button>\n  <tg-button type="callback_data" style="link" data="callback">callback</tg-button>\n</tg-button-row>\n<tg-button-row align="center">\n  <tg-button type="web_app" url="https://telegram.org">Mini App (private chats only)</tg-button>\n</tg-button-row>\n<tg-button-row align="right">\n  <tg-button type="switch_inline_query" query="inline">inline</tg-button>\n  <tg-button type="switch_inline_query_current_chat" query="inline 2">inline 2</tg-button>\n  <tg-button type="switch_inline_query_chosen_chat" query="inline 3" allow-user-chats allow-group-chats allow-channel-chats>inline 3</tg-button>\n</tg-button-row>\n<tg-button-row>\n  <tg-button type="copy_text" text="...copy">Copy</tg-button>\n  <tg-button type="disabled" style="primary">Disabled</tg-button>\n</tg-button-row>','10.3: this is the normal placement — group buttons into rows with tg-button-row, each row aligned left, center or right (default: left). Combine any action types per row: url, callback_data, web_app, the three switch_inline_query variants, copy_text and disabled. Use the button builder to select action, style and row. For buttons flowing inside text instead, see the inline Button guide above.','نسخه ۱۰.۳: این حالت عادی است — دکمه‌ها را با tg-button-row در ردیف‌هایی گروه کنید که هرکدام می‌توانند تراز چپ، وسط یا راست داشته باشند (پیش‌فرض: چپ). هر نوع عمل در هر ردیف قابل ترکیب است: url، callback_data، web_app، سه حالت switch_inline_query، copy_text و disabled. نوع، رنگ و شماره ردیف را در سازنده انتخاب کنید. برای دکمه‌های درون‌خطی به راهنمای «دکمه ریچ» بالا مراجعه کنید.'],
 ['InlineKeyboard','کیبورد اینلاین','<pre><code>{\n  "reply_markup": {\n    "inline_keyboard": [\n      [{ "text": "Open", "url": "https://t.me", "style": "primary" }],\n      [{ "text": "Confirm", "callback_data": "yes", "style": "success" }, { "text": "Cancel", "callback_data": "no", "style": "danger" }]\n    ]\n  }\n}</code></pre>','A real Telegram inline keyboard attaches below the message as reply_markup, separate from rich buttons inside the text. Since Bot API 9.4 each button also accepts an optional style of primary, success or danger; omit it for the client’s default look. Use the inline button builder to create one visually.','کیبورد اینلاین واقعی تلگرام با reply_markup زیر پیام می‌چسبد؛ جدا از دکمه‌های ریچ داخل متن است. از نسخه ۹.۴ هر دکمه می‌تواند رنگ اختیاری primary، success یا danger داشته باشد؛ برای نمایش پیش‌فرض کلاینت آن را خالی بگذارید. برای ساخت بصری از سازنده دکمه اینلاین استفاده کنید.'],
];
GUIDES.push(...blocks.map(([name,fa,code,description,descriptionFa])=>({name:'RichBlock'+name,fa,code,description,descriptionFa,group:['Map','Photo','Video','Audio','VoiceNote','Animation','Collage','Slideshow','Document'].includes(name)?'Media':'Blocks'})));
export const BUTTON_TYPES = ['url','callback_data','web_app','switch_inline_query','switch_inline_query_current_chat','switch_inline_query_chosen_chat','copy_text','disabled'];
export const BUTTON_DEMO = BUTTON_TYPES.map((type,i)=>`<tg-button type="${type}"${type==='callback_data'?' style="link" data="callback"':type==='copy_text'?' text="...copy"':type.startsWith('switch')?' style="primary" query="inline" allow-user-chats allow-bot-chats allow-group-chats allow-channel-chats':type==='disabled'?'':` style="${i%2?'danger':'success'}" url="https://${type==='web_app'?'telegram.org':'t.me'}"`}>${type==='callback_data'?'callback <tg-time unix="1647531900" format="wDT">22:45 tomorrow</tg-time> <tg-emoji emoji-id="5368324170671202286">👍</tg-emoji>':type.replace(/_/g,' ')}</tg-button>`).join('\n');
export const FULL_DEMO = '# TeleRich · The complete showcase\n\n'+GUIDES.map(g=>'## '+g.name+'\n\n'+g.code).join('\n\n')+'\n\n## All button actions\n'+BUTTON_DEMO;
export const RELEASES = [
 {version:'10.3',date:'August 24, 2026',anchor:'august-24-2026',items:[['Rich messages','RichMessageButton, RichTextButton, RichBlockButtons and InputRichBlockButtons. Compact tables (is_compact). Expandable block quotations. RichBlockDocument, InputRichBlockDocument and tg://document?id= links.','دکمه‌های ریچ و گروه دکمه، جدول فشرده، نقل‌قول بازشونده و اسناد با tg://document?id=.'],['Ephemeral messages','EphemeralMessageParameters replaces receiver_user_id and callback_query_id on send methods; sendRichMessage now accepts it. replace_callback_query_message replaces the original message. New file uploads in editEphemeralMessageMedia, show_caption_above_media in editEphemeralMessageCaption and rich_message in editEphemeralMessageText.','پارامتر یکپارچه پیام موقت؛ جایگزینی پیام اصلی، آپلود فایل در ویرایش مدیا و ویرایش متن ریچ و محل کپشن.'],['Reply markup & permissions','DisabledButton and InlineKeyboardButton.disabled. force_reply in InlineKeyboardMarkup and ReplyKeyboardMarkup. can_send_welcome_messages in administrator rights, ChatMemberAdministrator and promoteChatMember.','دکمه غیرفعال، force_reply در کیبوردها و مجوز ارسال پیام خوش‌آمدگویی مدیر.'],['Drafts & updates','can_stop and keep_on_stop in sendMessageDraft / sendRichMessageDraft. MessageGenerationStopped and Update.stopped_message_generation. CommunityChatJoined and Message.community_chat_joined. UniqueGiftInfo.text, entities and is_private.','توقف تولید پیش‌نویس و حفظ متن، آپدیت توقف تولید، پیوستن جامعه و فیلدهای جدید هدیه.']]},
 {version:'10.2',date:'July 14, 2026',anchor:'july-14-2026',items:[['Structured input & media','InputRichMessage now accepts blocks or explicit media mappings via InputRichMessageMedia. InputRichBlock classes cover paragraphs, headings, lists, quotations, tables, details, maps, media and thinking. InputMediaVoiceNote is available.','ورودی بلوکی پیام ریچ، نگاشت مدیا و کلاس‌های بلوکی برای قالب‌بندی متن و پیام صوتی.'],['Ephemeral messages','Private-to-user group messages: is_ephemeral, receiver_user and ephemeral_message_id. Edit text, media, caption and reply markup; delete with deleteEphemeralMessage. ReplyParameters can use ephemeral_message_id instead of message_id.','پیام گروهی خصوصی برای یک کاربر؛ ویرایش متن، مدیا، کپشن و کیبورد، حذف و پاسخ با شناسه پیام موقت.'],['Communities & security','Community, CommunityChatAdded/Removed and ChatFullInfo.community. BotSubscriptionUpdated in Update.subscription. Mini Apps restrict API calls from other origins starting July 20, 2026. Keep navigation on your original Mini App domain.','جوامع، رویدادهای افزودن و حذف چت و اشتراک؛ امنیت مبدأ مینی‌اپ از ۲۰ ژوئیه ۲۰۲۶.']]},
 {version:'10.1',date:'June 11, 2026',anchor:'june-11-2026',items:[['Rich messages introduced','RichText, RichBlock, RichMessage, InputRichMessage and InputRichMessageContent. sendRichMessage, sendRichMessageDraft and rich_message in editMessageText. Rich text supports all 26 original entity types and structured media blocks.','معرفی پیام ریچ، متن و بلوک، ارسال و استریم و ویرایش؛ ۲۶ نوع متن و بلوک‌های مدیا.'],['Join requests & polls','supports_join_request_queries, guard_bot, ChatJoinRequest.query_id. answerChatJoinRequestQuery and sendChatJoinRequestWebApp. PollMedia.link, Link and InputMediaLink in poll options.','کوئری درخواست عضویت، بات نگهبان و پاسخ درخواست؛ پشتیبانی پیوند در مدیای نظرسنجی.']]}
];
export const SETUP = [
 ['Create your Telegram bot','ساخت ربات تلگرام','Open @BotFather, run /newbot and copy the bot token. Never paste this token into the web editor.','در @BotFather دستور /newbot را بفرستید و توکن را بردارید. توکن را هرگز داخل ویرایشگر وب وارد نکنید.'],
 ['Download the two Worker modules','دریافت دو فایل Worker','Download worker.js and index.js below. index.js contains this self-contained web app and bilingual bot guides. Add both modules to a Cloudflare Worker; worker.js is the entry point.','دو فایل worker.js و index.js را دانلود کنید. index.js شامل وب و راهنمای ربات است. هر دو را در Worker اضافه کنید؛ worker.js فایل اصلی است.'],
 ['Configure secrets & access','تنظیم رازها و دسترسی','In Worker Settings → Variables and Secrets, add BOT_TOKEN, WEBHOOK_SECRET (a random secret), and ADMIN_KEY (a different strong secret for browser administration). Optional ADMINS_ID is a comma-separated list of Telegram user IDs. Unset means all authenticated Telegram users can use the bot; set means only listed users.','در تنظیمات Worker، رازهای BOT_TOKEN و WEBHOOK_SECRET و ADMIN_KEY را با مقدارهای متفاوت و قوی اضافه کنید. ADMINS_ID اختیاری و فهرست شناسه عددی با کاما است؛ خالی یعنی استفاده عمومی کاربران احراز هویت‌شده.'],
 ['Connect & register the webhook','اتصال و ثبت وب‌هوک','Deploy. In Settings here, enter the Worker HTTPS URL and ADMIN_KEY, then Test connection. Choose Register webhook to securely call setWebhook with secret_token and the /webhook endpoint. Check status with getWebhookInfo in the Telegram API if needed.','پس از استقرار، آدرس HTTPS و ADMIN_KEY را در تنظیمات اینجا وارد کنید و اتصال را بررسی کنید. ثبت وب‌هوک، setWebhook را با secret_token و مسیر /webhook اجرا می‌کند.'],
 ['Launch your Mini App','راه‌اندازی مینی‌اپ','In BotFather, use /setmenubutton and set the deployed Worker URL. Open the app from your bot. Telegram initData is validated on the server with HMAC and a one-hour expiration. In an external browser, ADMIN_KEY is required.','با /setmenubutton در BotFather آدرس Worker را تنظیم کنید. initData در سرور با HMAC و مهلت یک ساعت اعتبارسنجی می‌شود. مرورگر بیرونی به ADMIN_KEY نیاز دارد.'],
 ['Publish to a channel','انتشار در کانال','Add your bot as a channel administrator with permission to post. Open Channels, register @username or a -100… ID, and enable Send to channel in the composer. Mini App users must also be channel administrators. Channels and drafts are stored locally in this browser.','بات را مدیر کانال با مجوز ارسال کنید. در بخش کانال‌ها آدرس یا شناسه -100… را ثبت و ارسال به کانال را روشن کنید. کاربر مینی‌اپ هم باید مدیر کانال باشد. کانال‌ها و پیش‌نویس‌ها محلی ذخیره می‌شوند.'],
];
